version: '3.2'

services:

  database:
    image: mongo:3.4
    volumes:
      - /home/alexandre/Downloads/mongodb:/data/db/
    ports:
      - "27017:27017"

  app:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./src:/app
    working_dir: /app
